import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const css = readFileSync(new URL("../src/styles.css", import.meta.url), "utf8");
const app = readFileSync(new URL("../src/App.tsx", import.meta.url), "utf8");

test("the project drawer panes scroll the assignee list and the facts, not the member classes", () => {
  const start = css.indexOf(".drawer.project-detail-open {");
  assert.ok(start > 0, "expected the project two-pane rules");
  const media = css.slice(css.lastIndexOf("@media (min-width: 1052px) and (min-height: 720px)", start));
  const period = media.match(/\.project-detail-period \{([^}]+)\}/);
  const list = media.match(/\.project-detail-assignees \{([^}]+)\}/);
  const facts = media.match(/\.project-detail-facts \{([^}]+)\}/);
  assert.ok(period && list && facts);
  assert.match(period[1], /overflow:\s*hidden/);
  assert.match(list[1], /overflow:\s*auto/);
  assert.match(facts[1], /overflow:\s*auto/);
  assert.match(media, /\.drawer\.project-detail-open \.profile-capacity \{[^}]*display:\s*flex[^}]*flex-direction:\s*column/);
  const shell = media.match(/\.drawer\.project-detail-open \{([^}]+)\}/);
  assert.ok(shell);
  assert.match(shell[1], /height:\s*auto/);
  assert.match(shell[1], /max-height:\s*100%/);
  assert.match(shell[1], /align-self:\s*flex-start/);
  const columnRules = [...css.matchAll(/\.drawer\.project-detail-open \.profile-capacity \{([^}]+)\}/gu)];
  assert.equal(columnRules.length, 1);
  const afterListRule = css.slice(css.indexOf("border-right: 0;"), css.indexOf("border-right: 0;") + 700);
  assert.match(afterListRule, /\.drawer\.project-detail-open \.profile-capacity \{[^}]*display:\s*flex[^}]*flex-direction:\s*column/);
  assert.match(css, /\.project-detail \.drawer-section-title \{[^}]*margin-bottom:\s*12px/);
  assert.match(css, /\.project-detail \.detail-facts \{[^}]*padding:\s*16px[^}]*gap:\s*16px/);
  assert.match(css, /\.project-detail \.detail-member-list button \{[^}]*padding:\s*12px 14px/);
  assert.match(css, /\.project-detail \.profile-capacity \{[^}]*gap:\s*12px/);
  assert.match(css, /\.project-detail \.profile-capacity > div \{[^}]*72px minmax\(0, 1fr\) 80px/);
  assert.match(css, /\.project-detail \.detail-member-list small,\s*\.project-detail \.detail-need-list small,\s*\.project-detail \.profile-capacity span \{[^}]*word-break:\s*keep-all[^}]*overflow-wrap:\s*anywhere/);
  assert.match(css, /\.project-need-allocation \{[^}]*white-space:\s*nowrap/);
  assert.match(css, /\.project-detail \.detail-need-list \{[^}]*gap:\s*10px/);
  assert.match(css, /\.project-detail \.detail-need-list button \{[^}]*padding:\s*12px 14px/);
  assert.match(css, /\.project-detail \.profile-capacity i \{[^}]*height:\s*10px/);
  assert.match(css, /\.project-capacity-tick\[data-inside="true"\] \{[^}]*background:\s*var\(--paper\)/);
  assert.match(app, /capacityTickMarks/);
  assert.match(app, /className="project-capacity-tick"/);
  assert.match(app, /className="project-need-allocation"/);
  assert.match(app, /稼働配分 \$\{need\.allocation\}%/);
  assert.match(media, /\.drawer\.project-detail-open \.detail-member-list,\s*\.drawer\.project-detail-open \.detail-need-list \{[^}]*display:\s*flex[^}]*flex-direction:\s*column/);
  assert.equal(app.includes('className="project-detail"'), true);
  assert.equal(app.includes("project-detail-open"), true);
  assert.match(app, /\$\{count\}\/\$\{selectedProject\.demand\}名/);
  assert.match(app, /稼働配分 \$\{assignment\.allocation\}%/);
  assert.match(app, /稼働配分 \$\{need\.allocation\}%/);
  const from = app.indexOf('className="project-detail-assignees"');
  const scroll = app.slice(from, app.indexOf('className="project-detail-facts"', from));
  assert.match(scroll, /profile-capacity/);
  assert.match(scroll, /の担当/);
  const beforeScroll = app.slice(app.indexOf('className="project-detail-period"'), from);
  assert.match(beforeScroll, /の充足/);
  assert.equal(beforeScroll.includes("profile-capacity"), false);
  const projectFrom = app.indexOf('className="project-detail"');
  const projectBlock = app.slice(projectFrom, app.indexOf('drawer === "member"', projectFrom));
  assert.equal(projectBlock.includes("member-detail"), false);
  const projectCssStart = css.indexOf("/* Project detail (#439)");
  const projectCss = css.slice(projectCssStart, css.indexOf(".profile-skills", projectCssStart));
  assert.ok(projectCss.length > 0, "expected the project detail rules before .profile-skills");
  assert.equal(projectCss.includes("member-detail"), false);
});
